### PR TITLE
-added visualizer anaconda recipe

### PR DESCRIPTION
**Pull request by Thomas-Otto**

### CODE REVIEW

**Comment by rkaminsk** [comment]
Does not work for me. The problem is the entry point for `viz`. There is no `__main__.py` file. @pobermei Didn't you tell me that you wanted to put things into an asprilo namespace?

**Comment by pobermei** [comment]
> Does not work for me. The problem is the entry point for `viz`. There is no `__main__.py` file. \

@Thomas-Otto you forgot to define that file in your package

>@pobermei Didn't you tell me that you wanted to put things into an asprilo namespace?

Yes, for the future but not for now.

**Comment by rkaminsk** [comment]
> @Thomas-Otto you forgot to define that file in your package

Also, you are installing a script in your setup.py. I do not know how to make this work across platforms. Best use entry points. It is easy to use them with conda.

**Comment by pobermei** [comment]
> > @Thomas-Otto you forgot to define that file in your package
> 
> Also, you are installing a script in your setup.py. I do not know how to make this work across platforms. Best use entry points. It is easy to use them with conda.

That was the plan. @Thomas-Otto please fix accordingly. See my generator recipe and setup.py on as an example.

**Review by pobermei — APPROVED** [review]

**Comment by rkaminsk** [comment]
The `meta.yaml` looks fine now to me. But I noticed that the `setup.py` script (in the [develop](https://github.com/potassco/asprilo/blob/develop/visualizer/setup.py#L11) branch) still uses scripts, which installs unnecessary files. You should use entry points there too. Replace
```python
   scripts=['scripts/viz'],
```
by
```python
    entry_points = {
        'console_scripts': [
            'viz = visualizer.__main__:main',
            'viz-solver = visualizer.solver:main',
            'viz-simulator = visualizer.simulator:main'
        ]
    }
```
And please check, I have not tested this. Alternatively, you can leave out the scripts line altogether but you won't have the scripts then if you install the package with pip.

**Comment by rkaminsk** [comment]
Please notify me one this is done and best make a release so that I can upload a first anaconda package and give you access to it.

**Pull request merged**
